// Code generated by protoc-gen-go.
// source: pb.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	pb.proto

It has these top-level messages:
	LogEntry
	AppendEntriesRequest
	AppendEntriesResponse
	RequestVoteRequest
	RequestVoteResponse
	SnapshotRecoveryRequest
	SnapshotRecoveryResponse
	SnapshotRequest
	SnapshotResponse
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogEntry struct {
	Index            *uint64 `protobuf:"varint,1,req,name=Index" json:"Index,omitempty"`
	Term             *uint64 `protobuf:"varint,2,req,name=Term" json:"Term,omitempty"`
	CommandName      *string `protobuf:"bytes,3,req,name=CommandName" json:"CommandName,omitempty"`
	Command          []byte  `protobuf:"bytes,4,opt,name=Command" json:"Command,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogEntry) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *LogEntry) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *LogEntry) GetCommandName() string {
	if m != nil && m.CommandName != nil {
		return *m.CommandName
	}
	return ""
}

func (m *LogEntry) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

type AppendEntriesRequest struct {
	Term             *uint64     `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	PrevLogIndex     *uint64     `protobuf:"varint,2,req,name=PrevLogIndex" json:"PrevLogIndex,omitempty"`
	PrevLogTerm      *uint64     `protobuf:"varint,3,req,name=PrevLogTerm" json:"PrevLogTerm,omitempty"`
	CommitIndex      *uint64     `protobuf:"varint,4,req,name=CommitIndex" json:"CommitIndex,omitempty"`
	LeaderName       *string     `protobuf:"bytes,5,req,name=LeaderName" json:"LeaderName,omitempty"`
	Entries          []*LogEntry `protobuf:"bytes,6,rep,name=Entries" json:"Entries,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *AppendEntriesRequest) Reset()                    { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()               {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendEntriesRequest) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if m != nil && m.PrevLogIndex != nil {
		return *m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if m != nil && m.PrevLogTerm != nil {
		return *m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetCommitIndex() uint64 {
	if m != nil && m.CommitIndex != nil {
		return *m.CommitIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderName() string {
	if m != nil && m.LeaderName != nil {
		return *m.LeaderName
	}
	return ""
}

func (m *AppendEntriesRequest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResponse struct {
	Term             *uint64 `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	Index            *uint64 `protobuf:"varint,2,req,name=Index" json:"Index,omitempty"`
	CommitIndex      *uint64 `protobuf:"varint,3,req,name=CommitIndex" json:"CommitIndex,omitempty"`
	Success          *bool   `protobuf:"varint,4,req,name=Success" json:"Success,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppendEntriesResponse) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *AppendEntriesResponse) GetCommitIndex() uint64 {
	if m != nil && m.CommitIndex != nil {
		return *m.CommitIndex
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

type RequestVoteRequest struct {
	Term             *uint64 `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	LastLogIndex     *uint64 `protobuf:"varint,2,req,name=LastLogIndex" json:"LastLogIndex,omitempty"`
	LastLogTerm      *uint64 `protobuf:"varint,3,req,name=LastLogTerm" json:"LastLogTerm,omitempty"`
	CandidateName    *string `protobuf:"bytes,4,req,name=CandidateName" json:"CandidateName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestVoteRequest) Reset()                    { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()               {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestVoteRequest) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogIndex() uint64 {
	if m != nil && m.LastLogIndex != nil {
		return *m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() uint64 {
	if m != nil && m.LastLogTerm != nil {
		return *m.LastLogTerm
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateName() string {
	if m != nil && m.CandidateName != nil {
		return *m.CandidateName
	}
	return ""
}

type RequestVoteResponse struct {
	Term             *uint64 `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	VoteGranted      *bool   `protobuf:"varint,2,req,name=VoteGranted" json:"VoteGranted,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RequestVoteResponse) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil && m.VoteGranted != nil {
		return *m.VoteGranted
	}
	return false
}

type SnapshotRecoveryRequest struct {
	LeaderName       *string                         `protobuf:"bytes,1,req,name=LeaderName" json:"LeaderName,omitempty"`
	LastIndex        *uint64                         `protobuf:"varint,2,req,name=LastIndex" json:"LastIndex,omitempty"`
	LastTerm         *uint64                         `protobuf:"varint,3,req,name=LastTerm" json:"LastTerm,omitempty"`
	Peers            []*SnapshotRecoveryRequest_Peer `protobuf:"bytes,4,rep,name=Peers" json:"Peers,omitempty"`
	State            []byte                          `protobuf:"bytes,5,req,name=State" json:"State,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *SnapshotRecoveryRequest) Reset()                    { *m = SnapshotRecoveryRequest{} }
func (m *SnapshotRecoveryRequest) String() string            { return proto.CompactTextString(m) }
func (*SnapshotRecoveryRequest) ProtoMessage()               {}
func (*SnapshotRecoveryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SnapshotRecoveryRequest) GetLeaderName() string {
	if m != nil && m.LeaderName != nil {
		return *m.LeaderName
	}
	return ""
}

func (m *SnapshotRecoveryRequest) GetLastIndex() uint64 {
	if m != nil && m.LastIndex != nil {
		return *m.LastIndex
	}
	return 0
}

func (m *SnapshotRecoveryRequest) GetLastTerm() uint64 {
	if m != nil && m.LastTerm != nil {
		return *m.LastTerm
	}
	return 0
}

func (m *SnapshotRecoveryRequest) GetPeers() []*SnapshotRecoveryRequest_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *SnapshotRecoveryRequest) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

type SnapshotRecoveryRequest_Peer struct {
	Name             *string `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	ConnectionString *string `protobuf:"bytes,2,req,name=ConnectionString" json:"ConnectionString,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SnapshotRecoveryRequest_Peer) Reset()                    { *m = SnapshotRecoveryRequest_Peer{} }
func (m *SnapshotRecoveryRequest_Peer) String() string            { return proto.CompactTextString(m) }
func (*SnapshotRecoveryRequest_Peer) ProtoMessage()               {}
func (*SnapshotRecoveryRequest_Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *SnapshotRecoveryRequest_Peer) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *SnapshotRecoveryRequest_Peer) GetConnectionString() string {
	if m != nil && m.ConnectionString != nil {
		return *m.ConnectionString
	}
	return ""
}

type SnapshotRecoveryResponse struct {
	Term             *uint64 `protobuf:"varint,1,req,name=Term" json:"Term,omitempty"`
	Success          *bool   `protobuf:"varint,2,req,name=Success" json:"Success,omitempty"`
	CommitIndex      *uint64 `protobuf:"varint,3,req,name=CommitIndex" json:"CommitIndex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SnapshotRecoveryResponse) Reset()                    { *m = SnapshotRecoveryResponse{} }
func (m *SnapshotRecoveryResponse) String() string            { return proto.CompactTextString(m) }
func (*SnapshotRecoveryResponse) ProtoMessage()               {}
func (*SnapshotRecoveryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SnapshotRecoveryResponse) GetTerm() uint64 {
	if m != nil && m.Term != nil {
		return *m.Term
	}
	return 0
}

func (m *SnapshotRecoveryResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *SnapshotRecoveryResponse) GetCommitIndex() uint64 {
	if m != nil && m.CommitIndex != nil {
		return *m.CommitIndex
	}
	return 0
}

type SnapshotRequest struct {
	LeaderName       *string `protobuf:"bytes,1,req,name=LeaderName" json:"LeaderName,omitempty"`
	LastIndex        *uint64 `protobuf:"varint,2,req,name=LastIndex" json:"LastIndex,omitempty"`
	LastTerm         *uint64 `protobuf:"varint,3,req,name=LastTerm" json:"LastTerm,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SnapshotRequest) Reset()                    { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string            { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()               {}
func (*SnapshotRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SnapshotRequest) GetLeaderName() string {
	if m != nil && m.LeaderName != nil {
		return *m.LeaderName
	}
	return ""
}

func (m *SnapshotRequest) GetLastIndex() uint64 {
	if m != nil && m.LastIndex != nil {
		return *m.LastIndex
	}
	return 0
}

func (m *SnapshotRequest) GetLastTerm() uint64 {
	if m != nil && m.LastTerm != nil {
		return *m.LastTerm
	}
	return 0
}

type SnapshotResponse struct {
	Success          *bool  `protobuf:"varint,1,req,name=Success" json:"Success,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SnapshotResponse) Reset()                    { *m = SnapshotResponse{} }
func (m *SnapshotResponse) String() string            { return proto.CompactTextString(m) }
func (*SnapshotResponse) ProtoMessage()               {}
func (*SnapshotResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SnapshotResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "protobuf.LogEntry")
	proto.RegisterType((*AppendEntriesRequest)(nil), "protobuf.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "protobuf.AppendEntriesResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "protobuf.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "protobuf.RequestVoteResponse")
	proto.RegisterType((*SnapshotRecoveryRequest)(nil), "protobuf.SnapshotRecoveryRequest")
	proto.RegisterType((*SnapshotRecoveryRequest_Peer)(nil), "protobuf.SnapshotRecoveryRequest.Peer")
	proto.RegisterType((*SnapshotRecoveryResponse)(nil), "protobuf.SnapshotRecoveryResponse")
	proto.RegisterType((*SnapshotRequest)(nil), "protobuf.SnapshotRequest")
	proto.RegisterType((*SnapshotResponse)(nil), "protobuf.SnapshotResponse")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0xaa, 0xda, 0x40,
	0x18, 0x85, 0x89, 0xc6, 0x9a, 0xfc, 0x46, 0xb4, 0x51, 0x69, 0xe8, 0x4a, 0x46, 0x28, 0xae, 0xb2,
	0x28, 0x14, 0xba, 0x2d, 0x52, 0x4a, 0x8b, 0x15, 0x31, 0xa5, 0x8b, 0xee, 0x62, 0xf2, 0xd7, 0x66,
	0x91, 0x99, 0x74, 0x66, 0x94, 0xfa, 0x30, 0x7d, 0x9f, 0xfb, 0x58, 0x77, 0x66, 0x12, 0x35, 0x6a,
	0x5c, 0xdd, 0x95, 0x78, 0x1c, 0xce, 0xf9, 0xce, 0xf9, 0x05, 0xa7, 0xd8, 0x86, 0x05, 0x67, 0x92,
	0xf9, 0x8e, 0xf9, 0xd8, 0xee, 0x7f, 0x93, 0xef, 0xe0, 0x2c, 0xd9, 0xee, 0x33, 0x95, 0xfc, 0xe8,
	0xf7, 0xa1, 0xf3, 0x95, 0xa6, 0xf8, 0x2f, 0xb0, 0xa6, 0xad, 0xb9, 0xed, 0x7b, 0x60, 0xff, 0x40,
	0x9e, 0x07, 0x2d, 0xf3, 0x6d, 0x04, 0xbd, 0x05, 0xcb, 0xf3, 0x98, 0xa6, 0xab, 0x38, 0xc7, 0xa0,
	0xad, 0x44, 0xd7, 0x1f, 0x40, 0xb7, 0x12, 0x03, 0x7b, 0x6a, 0xcd, 0x3d, 0xf2, 0xdf, 0x82, 0xf1,
	0xa7, 0xa2, 0x40, 0x9a, 0x6a, 0xcb, 0x0c, 0xc5, 0x06, 0xff, 0xee, 0x51, 0xc8, 0xb3, 0x59, 0x69,
	0x3d, 0x06, 0x6f, 0xcd, 0xf1, 0xa0, 0x92, 0xcb, 0xc0, 0x73, 0x44, 0xa5, 0x9a, 0xa7, 0xed, 0x7a,
	0x6e, 0x26, 0xcb, 0x97, 0xb6, 0x11, 0x7d, 0x80, 0x25, 0xc6, 0x29, 0x72, 0xc3, 0xd2, 0x31, 0x2c,
	0x33, 0xe8, 0x56, 0x99, 0xc1, 0xab, 0x69, 0x7b, 0xde, 0x7b, 0xef, 0x87, 0xa7, 0x96, 0xe1, 0xa9,
	0x22, 0xf9, 0x05, 0x93, 0x1b, 0x3c, 0x51, 0x30, 0x2a, 0xf0, 0x86, 0xef, 0xbc, 0x44, 0xab, 0x89,
	0xa1, 0x04, 0x53, 0xdd, 0xa3, 0x7d, 0x92, 0xa0, 0x10, 0x06, 0xca, 0x21, 0x29, 0xf8, 0x55, 0xdb,
	0x9f, 0x4c, 0xe2, 0xc3, 0xe2, 0xcb, 0x58, 0xc8, 0xfb, 0xe2, 0x95, 0x5a, 0x2b, 0x3e, 0x81, 0xfe,
	0x42, 0x0d, 0x9b, 0xa5, 0xb1, 0x44, 0x53, 0x53, 0xa7, 0xb8, 0xe4, 0x23, 0x8c, 0xae, 0x52, 0x1a,
	0xf9, 0x95, 0xa1, 0xfe, 0xf5, 0x0b, 0x8f, 0xa9, 0xc4, 0xd4, 0xa4, 0x38, 0xe4, 0xc9, 0x82, 0x37,
	0x11, 0x8d, 0x0b, 0xf1, 0x87, 0xc9, 0x0d, 0x26, 0xec, 0x80, 0xfc, 0x78, 0xa2, 0xbc, 0x1e, 0xd4,
	0x32, 0x83, 0xbe, 0x06, 0x57, 0x53, 0xd5, 0x41, 0x87, 0xea, 0xdf, 0xa2, 0xa4, 0x1a, 0xe5, 0x07,
	0xe8, 0xac, 0x11, 0xb9, 0xde, 0x40, 0x6f, 0xfe, 0xee, 0xb2, 0xf9, 0x83, 0xa8, 0x50, 0x3f, 0xd7,
	0x03, 0x47, 0x52, 0x15, 0x33, 0xb7, 0xf3, 0xde, 0x86, 0x60, 0x1b, 0x59, 0xb5, 0xa8, 0x01, 0x04,
	0x30, 0x5c, 0x30, 0x4a, 0x31, 0x91, 0x19, 0xa3, 0x91, 0xba, 0x17, 0xdd, 0x19, 0x0e, 0x97, 0xac,
	0x20, 0xb8, 0xb7, 0x6f, 0x5c, 0xa2, 0x76, 0x25, 0xb3, 0x42, 0xe3, 0x2d, 0xc9, 0x37, 0x18, 0x5c,
	0xfc, 0x5e, 0xb6, 0x08, 0x99, 0xc1, 0xf0, 0xe2, 0x55, 0x31, 0xd5, 0x28, 0xb4, 0x93, 0xf3, 0x1c,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0x5e, 0x98, 0x39, 0x8b, 0x03, 0x00, 0x00,
}
